{{- if .Values.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "irdb-postgres.fullname" . }}-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "irdb-postgres.labels" . | nindent 4 }}
    cnpg.io/cluster: {{ include "irdb-postgres.clusterName" . }}
    {{- with .Values.nodePort.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.nodePort.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: NodePort
  {{- if .Values.nodePort.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.nodePort.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.nodePort.port }}
      targetPort: 5432
      protocol: TCP
      name: postgresql
      {{- if .Values.nodePort.nodePort }}
      nodePort: {{ .Values.nodePort.nodePort }}
      {{- end }}
  selector:
    cnpg.io/cluster: {{ include "irdb-postgres.clusterName" . }}
    cnpg.io/instanceRole: primary
{{- end }}
