apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: irdb

resources:
  - namespace.yaml
  - secret.yaml
  - cluster.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: irdb-postgres
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: cloudnativepg
