apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: irdb

resources:
  - ../../base

# Development-specific patches
patchesStrategicMerge:
  - cluster-patch.yaml

labels:
  - pairs:
      environment: dev
